# Generated by Django 5.1.6 on 2025-03-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("organisation_name", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=100)),
                (
                    "annual_income",
                    models.CharField(
                        choices=[
                            ("under_500k", "Less than £500K"),
                            ("max_1m", "£500K - £1million"),
                            ("max_3m", "£1 million - £3 million"),
                            ("max_10m", "£3 million - £10 million"),
                            ("over_10m", "Over £10 million"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fundraisers", models.CharField(max_length=20)),
                ("support_needs", models.TextField()),
                ("privacy_policy", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
