# Generated by Django 5.1.6 on 2025-03-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_content_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("template", "Template"),
                    ("article", "Article"),
                    ("blog", "Blog"),
                ],
                default="Article",
                max_length=50,
            ),
        ),
    ]
