# Generated by Django 5.1.6 on 2025-03-26 11:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"], "verbose_name_plural": "Posts"},
        ),
        migrations.AddField(
            model_name="post",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image for cards and previews (Recommended: 1200x630px)",
                null=True,
                upload_to="blog/main_images/",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
