# Generated by Django 5.1.6 on 2025-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.CharField(
                help_text="Insert summary of article for SEO purposes.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="main_image",
            field=models.ImageField(
                blank=True,
                default="Summary",
                help_text="Featured image for cards and previews (Recommended: 1200x630px).",
                null=True,
                upload_to="blog/main_images/",
            ),
        ),
    ]
