# Generated by Django 5.1.6 on 2025-03-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("url", models.URLField()),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        default="Summary",
                        help_text="Featured image for cards and previews (Recommended: 1200x630px).",
                        null=True,
                        upload_to="training/main_images/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Trainings",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.DeleteModel(
            name="TrainingEvent",
        ),
    ]
