# Generated by Django 5.1.6 on 2025-03-30 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_training_delete_trainingevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
